import type { SettingCategory, SettingSection } from "@/types/settings-schema";
import { useSettingsStore } from "@/stores/settings";
import { isMac } from "@/utils/config";
import IconLucideMonitor from "~icons/lucide/monitor";

const desktopLyricSection: SettingSection = {
  id: "desktopLyric",
  tag: { text: "Beta" },
  items: [
    {
      key: "desktopLyricEnabled",
      type: "switch",
      binding: { store: "settings", path: "isDesktopLyricOpen" },
      defaultValue: false,
    },
    {
      key: "desktopLyricFontSize",
      type: "select",
      binding: { store: "settings", path: "system.desktopLyric.fontSize" },
      defaultValue: 24,
      options: Array.from({ length: 96 - 20 + 1 }, (_, i) => {
        const n = 20 + i;
        return { value: n, label: `${n} px` };
      }),
    },
    {
      key: "desktopLyricFontWeight",
      type: "slider",
      binding: { store: "settings", path: "system.desktopLyric.fontWeight" },
      min: 100,
      max: 900,
      step: 100,
      defaultValue: 600,
      marks: { 100: "100", 400: "400", 700: "700", 900: "900" },
    },
    {
      key: "desktopLyricDoubleLine",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.doubleLine" },
      defaultValue: true,
    },
    {
      key: "desktopLyricAlign",
      type: "select",
      binding: { store: "settings", path: "system.desktopLyric.align" },
      options: [
        { value: "left", labelKey: "settings.desktopLyricAlign.left" },
        { value: "center", labelKey: "settings.desktopLyricAlign.center" },
        { value: "right", labelKey: "settings.desktopLyricAlign.right" },
        { value: "justify", labelKey: "settings.desktopLyricAlign.justify" },
      ],
      defaultValue: "center",
    },
    {
      key: "desktopLyricWordByWord",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.wordByWord" },
      defaultValue: true,
    },
    {
      key: "desktopLyricAutoGenerateWordByWord",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.autoGenerateWordByWord" },
      defaultValue: true,
    },
    {
      key: "desktopLyricShowTranslation",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.showTranslation" },
      defaultValue: true,
    },
    {
      key: "desktopLyricPlayedColor",
      type: "color",
      binding: { store: "settings", path: "system.desktopLyric.playedColor" },
      defaultValue: "#ffffff",
      showAlpha: false,
    },
    {
      key: "desktopLyricUnplayedColor",
      type: "color",
      binding: { store: "settings", path: "system.desktopLyric.unplayedColor" },
      defaultValue: "#7d7d7d",
      showAlpha: false,
    },
    {
      key: "desktopLyricStrokeColor",
      type: "color",
      binding: { store: "settings", path: "system.desktopLyric.strokeColor" },
      defaultValue: "rgba(0, 0, 0, 0.5)",
    },
    {
      key: "desktopLyricBackgroundColor",
      type: "color",
      binding: { store: "settings", path: "system.desktopLyric.backgroundColor" },
      defaultValue: "rgba(0, 0, 0, 0)",
    },
    {
      key: "desktopLyricBackgroundMask",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.backgroundMask" },
      defaultValue: false,
      children: [
        {
          key: "desktopLyricBackgroundMaskColor",
          type: "color",
          binding: { store: "settings", path: "system.desktopLyric.backgroundMaskColor" },
          defaultValue: "rgba(0, 0, 0, 0.3)",
        },
      ],
    },
    {
      key: "desktopLyricAlwaysShowSongInfo",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.alwaysShowSongInfo" },
      defaultValue: false,
    },
    {
      key: "desktopLyricAnimation",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.animation" },
      defaultValue: true,
    },
    {
      key: "desktopLyricLimitBounds",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.limitBounds" },
      defaultValue: false,
    },
    {
      key: "desktopLyricAlwaysOnTop",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.alwaysOnTop" },
      defaultValue: true,
    },
    {
      key: "desktopLyricLocked",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.locked" },
      defaultValue: false,
    },
    {
      key: "desktopLyricUseCSSDrag",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.useCSSDrag" },
      defaultValue: false,
    },
    {
      key: "desktopLyricEnableSpectrum",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.enableSpectrum" },
      defaultValue: false,
      children: [
        {
          key: "desktopLyricSpectrumColor",
          type: "color",
          binding: { store: "settings", path: "system.desktopLyric.spectrumColor" },
          defaultValue: "rgba(255, 255, 255, 0.6)",
        },
        {
          key: "desktopLyricSpectrumHeight",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.spectrumHeight" },
          min: 20,
          max: 120,
          step: 5,
          defaultValue: 60,
          marks: { 20: "20", 60: "60", 120: "120" },
        },
        {
          key: "desktopLyricSpectrumOpacity",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.spectrumOpacity" },
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.6,
          marks: { 0: "0", 0.5: "0.5", 1: "1" },
        },
        {
          key: "desktopLyricSpectrumRadius",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.spectrumRadius" },
          min: 0,
          max: 10,
          step: 1,
          defaultValue: 2,
          marks: { 0: "0", 5: "5", 10: "10" },
        },
      ],
    },
    {
      key: "desktopLyricImmersiveMode",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.immersiveMode" },
      defaultValue: false,
      children: [
        {
          key: "desktopLyricImmersiveBlur",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.immersiveBlur" },
          min: 0,
          max: 40,
          step: 2,
          defaultValue: 20,
          marks: { 0: "0", 20: "20", 40: "40" },
        },
        {
          key: "desktopLyricImmersiveDim",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.immersiveDim" },
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.5,
          marks: { 0: "0", 0.5: "0.5", 1: "1" },
        },
        {
          key: "desktopLyricImmersiveScale",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.immersiveScale" },
          min: 1,
          max: 2,
          step: 0.05,
          defaultValue: 1.15,
          marks: { 1: "1x", 1.5: "1.5x", 2: "2x" },
        },
      ],
    },
    {
      key: "desktopLyricLineSpacing",
      type: "slider",
      binding: { store: "settings", path: "system.desktopLyric.lineSpacing" },
      min: 0,
      max: 40,
      step: 1,
      defaultValue: 8,
      marks: { 0: "0", 20: "20", 40: "40" },
    },
    {
      key: "desktopLyricGlowEffect",
      type: "switch",
      binding: { store: "settings", path: "system.desktopLyric.glowEffect" },
      defaultValue: false,
      children: [
        {
          key: "desktopLyricGlowColor",
          type: "color",
          binding: { store: "settings", path: "system.desktopLyric.glowColor" },
          defaultValue: "rgba(255, 255, 255, 0.3)",
        },
        {
          key: "desktopLyricGlowIntensity",
          type: "slider",
          binding: { store: "settings", path: "system.desktopLyric.glowIntensity" },
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.3,
          marks: { 0: "0", 0.5: "0.5", 1: "1" },
        },
      ],
    },
  ],
};

const dynamicIslandSection: SettingSection = {
  id: "dynamicIsland",
  tag: { text: "Beta" },
  items: [
    {
      key: "dynamicIslandEnabled",
      type: "switch",
      binding: { store: "settings", path: "isDynamicIslandOpen" },
      defaultValue: false,
    },
    {
      key: "dynamicIslandScale",
      type: "slider",
      binding: { store: "settings", path: "system.dynamicIsland.scale" },
      min: 0.5,
      max: 2,
      step: 0.05,
      defaultValue: 1,
      marks: { 0.5: "50%", 1: "100%", 2: "200%" },
    },
    {
      key: "dynamicIslandFontWeight",
      type: "slider",
      binding: { store: "settings", path: "system.dynamicIsland.fontWeight" },
      min: 100,
      max: 900,
      step: 100,
      defaultValue: 500,
      marks: { 100: "100", 500: "500", 900: "900" },
    },
    {
      key: "dynamicIslandWordByWord",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.wordByWord" },
      defaultValue: true,
    },
    {
      key: "dynamicIslandDoubleLine",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.doubleLine" },
      defaultValue: false,
    },
    {
      key: "dynamicIslandShowTranslation",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.showTranslation" },
      defaultValue: false,
    },
    {
      key: "dynamicIslandPlayedColor",
      type: "color",
      binding: { store: "settings", path: "system.dynamicIsland.playedColor" },
      defaultValue: "rgba(255, 255, 255, 1)",
      showAlpha: false,
    },
    {
      key: "dynamicIslandUnplayedColor",
      type: "color",
      binding: { store: "settings", path: "system.dynamicIsland.unplayedColor" },
      defaultValue: "rgba(255, 255, 255, 0.5)",
    },
    {
      key: "dynamicIslandBackgroundColor",
      type: "color",
      binding: { store: "settings", path: "system.dynamicIsland.backgroundColor" },
      defaultValue: "rgba(0, 0, 0, 1)",
    },
    {
      key: "dynamicIslandAlwaysOnTop",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.alwaysOnTop" },
      defaultValue: true,
    },
    ...(isMac
      ? [
          {
            key: "dynamicIslandNotchFusion",
            type: "switch" as const,
            binding: { store: "settings" as const, path: "system.dynamicIsland.notchFusion" },
            defaultValue: false,
          },
        ]
      : []),
    {
      key: "dynamicIslandSnapCentered",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.snapCentered" },
      defaultValue: true,
      disabled: () => useSettingsStore().system.dynamicIsland.notchFusion,
    },
    {
      key: "dynamicIslandNonOcclusive",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.nonOcclusive" },
      defaultValue: false,
    },
    {
      key: "dynamicIslandUseCSSDrag",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.useCSSDrag" },
      defaultValue: false,
    },
    {
      key: "dynamicIslandShowCover",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.showCover" },
      defaultValue: true,
    },
    {
      key: "dynamicIslandCoverBorderRadius",
      type: "slider",
      binding: { store: "settings", path: "system.dynamicIsland.coverBorderRadius" },
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 6,
      marks: { 0: "0", 10: "10", 20: "20" },
    },
    {
      key: "dynamicIslandGlowEffect",
      type: "switch",
      binding: { store: "settings", path: "system.dynamicIsland.glowEffect" },
      defaultValue: false,
      children: [
        {
          key: "dynamicIslandGlowColor",
          type: "color",
          binding: { store: "settings", path: "system.dynamicIsland.glowColor" },
          defaultValue: "rgba(255, 255, 255, 0.3)",
        },
        {
          key: "dynamicIslandGlowIntensity",
          type: "slider",
          binding: { store: "settings", path: "system.dynamicIsland.glowIntensity" },
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.3,
          marks: { 0: "0", 0.5: "0.5", 1: "1" },
        },
      ],
    },
    {
      key: "dynamicIslandHorizontalPadding",
      type: "slider",
      binding: { store: "settings", path: "system.dynamicIsland.horizontalPadding" },
      min: 0,
      max: 40,
      step: 2,
      defaultValue: 0,
      marks: { 0: "0", 20: "20", 40: "40" },
    },
    {
      key: "dynamicIslandVerticalPadding",
      type: "slider",
      binding: { store: "settings", path: "system.dynamicIsland.verticalPadding" },
      min: 0,
      max: 40,
      step: 2,
      defaultValue: 0,
      marks: { 0: "0", 20: "20", 40: "40" },
    },
  ],
};

/** Win 平台限定 */
const taskbarLyricSection: SettingSection = {
  id: "taskbarLyric",
  tag: { text: "Beta" },
  items: [
    {
      key: "taskbarLyricEnabled",
      type: "switch",
      binding: { store: "settings", path: "isTaskbarLyricOpen" },
      defaultValue: false,
    },
    {
      key: "taskbarLyricPosition",
      type: "select",
      binding: { store: "settings", path: "system.taskbarLyric.position" },
      options: [
        { value: "auto", labelKey: "settings.taskbarLyricPosition.auto" },
        { value: "left", labelKey: "settings.taskbarLyricPosition.left" },
        { value: "right", labelKey: "settings.taskbarLyricPosition.right" },
      ],
      defaultValue: "auto",
    },
    {
      key: "taskbarLyricAutoMaxWidth",
      type: "switch",
      binding: { store: "settings", path: "system.taskbarLyric.autoMaxWidth" },
      defaultValue: true,
      childrenCondition: () => useSettingsStore().system.taskbarLyric.autoMaxWidth === false,
      children: [
        {
          key: "taskbarLyricMaxWidth",
          type: "slider",
          binding: { store: "settings", path: "system.taskbarLyric.maxWidth" },
          min: 200,
          max: 800,
          step: 20,
          defaultValue: 400,
          marks: { 200: "200", 400: "400", 800: "800" },
        },
      ],
    },
    {
      key: "taskbarLyricLeftMargin",
      type: "number",
      binding: { store: "settings", path: "system.taskbarLyric.leftMargin" },
      min: 0,
      max: 500,
      defaultValue: 0,
    },
    {
      key: "taskbarLyricRightMargin",
      type: "number",
      binding: { store: "settings", path: "system.taskbarLyric.rightMargin" },
      min: 0,
      max: 500,
      defaultValue: 0,
    },
    {
      key: "taskbarLyricColorMode",
      type: "select",
      binding: { store: "settings", path: "system.taskbarLyric.colorMode" },
      options: [
        { value: "taskbar", labelKey: "settings.taskbarLyricColorMode.taskbar" },
        { value: "taskbarInverse", labelKey: "settings.taskbarLyricColorMode.taskbarInverse" },
        { value: "light", labelKey: "settings.taskbarLyricColorMode.light" },
        { value: "dark", labelKey: "settings.taskbarLyricColorMode.dark" },
      ],
      defaultValue: "taskbar",
    },
    {
      key: "taskbarLyricFontSize",
      type: "slider",
      binding: { store: "settings", path: "system.taskbarLyric.fontSize" },
      min: 12,
      max: 20,
      step: 1,
      defaultValue: 14,
      marks: { 12: "12", 14: "14", 17: "17", 20: "20" },
    },
    {
      key: "taskbarLyricShowCover",
      type: "switch",
      binding: { store: "settings", path: "system.taskbarLyric.showCover" },
      defaultValue: true,
    },
    {
      key: "taskbarLyricWordByWord",
      type: "switch",
      binding: { store: "settings", path: "system.taskbarLyric.wordByWord" },
      defaultValue: true,
    },
    {
      key: "taskbarLyricDoubleLine",
      type: "switch",
      binding: { store: "settings", path: "system.taskbarLyric.doubleLine" },
      defaultValue: true,
    },
    {
      key: "taskbarLyricShowTranslation",
      type: "switch",
      binding: { store: "settings", path: "system.taskbarLyric.showTranslation" },
      defaultValue: true,
    },
  ],
};

const externalLyricCategory: SettingCategory = {
  id: "externalLyric",
  icon: IconLucideMonitor,
  sections: [
    desktopLyricSection,
    dynamicIslandSection,
    // taskbarLyric 仅 Windows 可用
    ...(navigator.platform.startsWith("Win") ? [taskbarLyricSection] : []),
  ],
};

export default externalLyricCategory;
