import type { SystemConfig } from "../types/settings";
import { defaultPluginsConfig } from "./plugin-api";
import { defaultHotkeyConfig } from "./hotkeys";

/**
 * 灵动岛基准高度（缩放比例 = 1 时的物理像素，等于"主行高度")
 * 主行高度 = DYNAMIC_ISLAND_BASE_HEIGHT * scale
 * 双行模式下窗口最终高度 = 主行高度 + 副行高度
 * 主进程按渲染端上报的最终高度 setBounds
 */
export const DYNAMIC_ISLAND_BASE_HEIGHT = 40;

/** 默认配置 */
export const defaultSystemConfig: SystemConfig = {
  player: {
    autoPlay: false,
    rememberLastTrack: true,
    fadeEnabled: true,
    fadeDuration: 200,
    outputDevice: null,
    volume: 1,
    loudnessNormalization: false,
    equalizer: {
      enabled: false,
      preset: "flat",
      bands: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      preamp: 0,
    },
    lyricOffsets: {},
  },
  media: {
    systemMediaControls: true,
    discord: {
      enabled: false,
      showWhenPaused: false,
      displayMode: "name",
    },
  },
  library: {
    scanDirs: [],
  },
  desktopLyric: {
    fontSize: 24,
    fontWeight: 600,
    fontFamily: "",
    showTranslation: true,
    doubleLine: true,
    align: "center",
    wordByWord: true,
    autoGenerateWordByWord: true,
    playedColor: "rgb(254, 121, 113)",
    unplayedColor: "rgb(255, 255, 255)",
    strokeColor: "rgba(0, 0, 0, 0.5)",
    backgroundColor: "rgba(0, 0, 0, 0)",
    backgroundOpacity: 0,
    backgroundMask: false,
    backgroundMaskColor: "rgba(0, 0, 0, 0.3)",
    alwaysShowSongInfo: false,
    limitBounds: false,
    animation: true,
    alwaysOnTop: true,
    locked: false,
    useCSSDrag: false,
    enableSpectrum: false,
    spectrumColor: "rgba(255, 255, 255, 0.6)",
    spectrumHeight: 60,
    spectrumOpacity: 0.6,
    spectrumRadius: 2,
    immersiveMode: false,
    immersiveBlur: 20,
    immersiveDim: 0.5,
    immersiveScale: 1.15,
    lineSpacing: 8,
    glowEffect: false,
    glowColor: "rgba(255, 255, 255, 0.3)",
    glowIntensity: 0.3,
  },
  dynamicIsland: {
    scale: 1,
    fontWeight: 500,
    fontFamily: "",
    wordByWord: true,
    playedColor: "rgba(255, 255, 255, 1)",
    unplayedColor: "rgba(255, 255, 255, 0.5)",
    backgroundColor: "rgba(0, 0, 0, 1)",
    alwaysOnTop: true,
    snapCentered: true,
    notchFusion: false,
    nonOcclusive: false,
    doubleLine: false,
    showTranslation: false,
    useCSSDrag: false,
    showCover: true,
    coverBorderRadius: 6,
    glowEffect: false,
    glowColor: "rgba(255, 255, 255, 0.3)",
    glowIntensity: 0.3,
    horizontalPadding: 0,
    verticalPadding: 0,
  },
  taskbarLyric: {
    position: "auto",
    autoMaxWidth: true,
    maxWidth: 400,
    leftMargin: 0,
    rightMargin: 0,
    colorMode: "taskbar",
    doubleLine: true,
    showTranslation: true,
    showCover: true,
    wordByWord: true,
    fontSize: 14,
    fontFamily: "",
  },
  lyric: {
    enableOnlineTTMLLyric: false,
    amllDbServer: "https://amlldb.bikonoo.com/%p/%s.ttml",
  },
  localLyric: {
    enableLocalTTMLOverride: false,
    repoDir: "",
  },
  cache: {
    dir: null,
    songCache: {
      enabled: false,
      sizeLimitGb: 10,
    },
  },
  download: {
    enabled: false,
    dir: null,
    quality: "lossless",
    usePlaybackForDownload: false,
    fileTemplate: "{artist} - {title}",
    folderScheme: "none",
    overwritePolicy: "rename",
    embedCover: true,
    embedMeta: true,
    embedLyric: true,
    writeLrc: false,
    saveTtml: false,
    lyricFileFormat: "enhanced-lrc",
  },
  streaming: {
    enabled: true,
  },
  lastfm: {
    enabled: false,
    scrobble: true,
    nowPlaying: true,
    loveSync: true,
  },
  externalApi: {
    enabled: false,
    wsEnabled: false,
    allowLan: false,
    port: 14558,
  },
  update: {
    autoCheck: true,
  },
  system: {
    rememberWindowState: true,
    taskbarProgress: true,
    taskbarThumbnailCover: true,
    uiZoom: 100,
    onboardingCompleted: false,
    neteaseRealIp: false,
    neteaseScrobbleEnabled: false,
    neteaseScrobbleMode: "ncbl",
    registerOrpheusProtocol: false,
  },
  windowStates: {
    main: {
      width: 1280,
      height: 800,
      x: null,
      y: null,
      maximized: false,
    },
    desktopLyric: {
      width: 800,
      height: 200,
      x: null,
      y: null,
      visible: false,
    },
    dynamicIsland: {
      mode: "snapped",
      x: null,
      y: null,
      visible: false,
    },
    taskbarLyric: {
      visible: false,
    },
  },
  plugins: defaultPluginsConfig,
  hotkeys: defaultHotkeyConfig,
};
