/* auto-generated by NAPI-RS */
/* eslint-disable */
/** * 检测当前是否在 Wayland 环境下运行
 * @returns true 表示检测到 Wayland
 */
export declare function isWayland(): boolean

/** * 检测当前是否在 X11 环境下运行
 * @returns true 表示检测到 X11
 */
export declare function isX11(): boolean

/** * 通过 X11 _NET_WM_STATE 设置窗口置顶/取消置顶
 * @param window_id - X11 Window ID（Electron getNativeWindowHandle() 返回值）
 * @param enable - true 设置置顶，false 取消置顶
 */
export declare function setAlwaysOnTopX11(windowId: number, enable: boolean): void

/** * 通过 X11 Shape 扩展设置鼠标事件穿透/恢复
 * Electron 的 setIgnoreMouseEvents 在 Linux transparent 窗口上可能不生效，
 * 通过 XShape ShapeInput 直接设置输入区域为空来绕过
 * @param window_id - X11 Window ID
 * @param ignore - true 忽略鼠标事件（穿透），false 恢复
 */
export declare function setIgnoreMouseEventsX11(windowId: number, ignore: boolean): void
